application: mylanhack
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: bootstrap

- url: /css
  static_dir: css

- url: /form
  static_dir: form

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /twitter
  static_dir: twitter

- url: .*
  static_files: index.html
  upload: index\.html
